In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read.csv("water_usage_prediction.csv")
df.head()

AttributeError: module 'pandas' has no attribute 'read'

In [ ]:
df = pd.read.csv("water_usage_prediction.csv")

AttributeError: module 'pandas' has no attribute 'read'

In [ ]:
df = pd.read_csv("water_usage_prediction.csv")

In [ ]:
df.head()

,State,Year,Population (millions),Annual Rainfall (mm),Agricultural Land (sq km),Industrial Water Usage (billion liters),Domestic Water Usage (billion liters),Total Water Consumption (billion liters)
0,Himachal Pradesh,2014,62.06,2335.9,27858.7,217.78,173.96,391.74
1,Maharashtra,2023,161.10,2896.7,4921.7,283.42,169.84,453.26
2,Tamil Nadu,2003,249.33,653.0,29305.3,257.51,257.38,514.89
3,Haryana,2016,37.34,972.3,71026.8,204.25,218.42,422.67
4,Chhattisgarh,2006,152.04,825.5,174406.8,281.18,27.66,308.84

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   State                                     5000 non-null   object
 1   Year                                      5000 non-null   int64
 2   Population (millions)                     5000 non-null   float64
 3   Annual Rainfall (mm)                      5000 non-null   float64
 4   Agricultural Land (sq km)                 5000 non-null   float64
 5   Industrial Water Usage (billion liters)   5000 non-null   float64
 6   Domestic Water Usage (billion liters)     5000 non-null   float64
 7   Total Water Consumption (billion liters)  5000 non-null   float64
dtypes: float64(6), int64(1), object(1)
memory usage: 312.6+ KB

AttributeError: 'DataFrame' object has no attribute 'descr'

In [ ]:
df.drop(columns="Year",inplace=True)

In [ ]:
df.head()

,State,Population (millions),Annual Rainfall (mm),Agricultural Land (sq km),Industrial Water Usage (billion liters),Domestic Water Usage (billion liters),Total Water Consumption (billion liters)
0,Himachal Pradesh,62.06,2335.9,27858.7,217.78,173.96,391.74
1,Maharashtra,161.10,2896.7,4921.7,283.42,169.84,453.26
2,Tamil Nadu,249.33,653.0,29305.3,257.51,257.38,514.89
3,Haryana,37.34,972.3,71026.8,204.25,218.42,422.67
4,Chhattisgarh,152.04,825.5,174406.8,281.18,27.66,308.84

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['State'] = label_encoder.fit_transform(df['State'])

In [ ]:
print("Model function")